development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: movie_data_development
  pool: 5
  username: root
  password: supu123
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: movie_data_test
  pool: 5
  username: root
  password: supu123
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: movie_data_production
  pool: 5
  username: root
  password: supu123
  socket: /var/run/mysqld/mysqld.sock
